# Exercise

Ok, its time to practice what we just covered in the Opening and reading files chapter. We are going to use pandas to open a csv and then proceed to carry out a bit.

Let's start off by downloading the csv combined_indicators_for_nigeria_2. This is a csv file, read the file using pandas.

- Print the first 5 columns in the dataframe and the name of all the columns
- in addition to this change the column <strong><i>country_iso3</i></strong> to <strong><i>country iso code</i></strong>

In [81]:
# path = 'C://Users//User//Documents//GradientBoostCurriculum//GradientBoostIntrotoDS//Introduction to Python//Chapter 3 - File Handling, Introduction to Pandas//combined_indicators_for_nigeria_2.csv'
# import pandas as pd
# df = pd.read_csv(path)

import numpy as np
import pandas as pd
df=pd.read_csv('combined_indicators_for_nigeria_2.csv')
df.rename(columns={'country_iso3':'country iso code'},inplace=True)
df.head()

,country_name,country iso code,year,indicator_name,indicator_code,value
0,Nigeria,NGA,2007,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,24800.0
1,Nigeria,NGA,2006,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,23999.0
2,Nigeria,NGA,2005,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,23000.0
3,Nigeria,NGA,2004,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,23000.0
4,Nigeria,NGA,2003,"Agricultural machinery, tractors",AG.AGR.TRAC.NO,22000.0

# Question 1

Select data in your dataframe where the indicator name is;
- "Net bilateral aid flows from DAC donors, Australia (current US$) or
- Net bilateral aid flows from DAC donors, United Kingdomor
- Net bilateral aid flows from DAC donors, United States or 
- Net bilateral aid flows from DAC donors, European Union institutions

Save this as western_dac_donors

In [49]:
western_dac_donors = df.loc[df['indicator_name'].isin(['Net bilateral aid flows from DAC donors, Australia (current US$)',
          'Net bilateral aid flows from DAC donors, United Kingdom (current US$)',
         'Net bilateral aid flows from DAC donors, United States (current US$)',
         'Net bilateral aid flows from DAC donors, European Union institutions (current US$)'])]
western_dac_donors.head()

,country_name,country iso code,year,indicator_name,indicator_code,value
1760,Nigeria,NGA,2017,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,8780000.0
1761,Nigeria,NGA,2016,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,1680000.0
1762,Nigeria,NGA,2015,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,2090000.0
1763,Nigeria,NGA,2014,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,2380000.0
1764,Nigeria,NGA,2013,"Net bilateral aid flows from DAC donors, Austr...",DC.DAC.AUSL.CD,3670000.0

# Question 2

Great, now select the rows where the indicator_name relates to Net officual flows from UN agencies, save this subset as un_agencies_donor

In [51]:
un_agencies_donor = df.loc[df['indicator_name'].isin(['Net official flows from UN agencies, UNICEF (current US$)',
                                                     'Net official flows from UN agencies, UNHCR (current US$)',
                                                     'Net official flows from UN agencies, UNDP (current US$)',
                                                     'Net official flows from UN agencies, UNFPA (current US$)',
                                                     'Net official flows from UN agencies, UNTA (current US$)',
                                                     'Net official flows from UN agencies, WFP (current US$)',
                                                     'Net official flows from UN agencies, WHO (current US$)'])]
un_agencies_donor.head()

,country_name,country iso code,year,indicator_name,indicator_code,value
2955,Nigeria,NGA,2017,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,55020000.0
2956,Nigeria,NGA,2016,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,57920000.0
2957,Nigeria,NGA,2015,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,48950000.0
2958,Nigeria,NGA,2014,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,56020000.0
2959,Nigeria,NGA,2013,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,56810000.0

# Question 3

Select all the rows in un_agencies_donor where the year is greater than or equal to 2015, sort these rows by <strong>value</strong> in descending order ie. starting with the largest value

In [53]:
un_agencies_donor
un_agencies_donor[un_agencies_donor.iloc[:,2] >= 2015]

,country_name,country iso code,year,indicator_name,indicator_code,value
2955,Nigeria,NGA,2017,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,55020000.0
2956,Nigeria,NGA,2016,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,57920000.0
2957,Nigeria,NGA,2015,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,48950000.0
3003,Nigeria,NGA,2015,"Net official flows from UN agencies, UNHCR (cu...",DT.NFL.UNCR.CD,1390000.0
3040,Nigeria,NGA,2017,"Net official flows from UN agencies, UNDP (cur...",DT.NFL.UNDP.CD,5240000.0
3041,Nigeria,NGA,2016,"Net official flows from UN agencies, UNDP (cur...",DT.NFL.UNDP.CD,9690000.0
3042,Nigeria,NGA,2015,"Net official flows from UN agencies, UNDP (cur...",DT.NFL.UNDP.CD,9860000.0
3090,Nigeria,NGA,2017,"Net official flows from UN agencies, UNFPA (cu...",DT.NFL.UNFP.CD,6100000.0
3091,Nigeria,NGA,2016,"Net official flows from UN agencies, UNFPA (cu...",DT.NFL.UNFP.CD,5970000.0
3092,Nigeria,NGA,2015,"Net official flows from UN agencies, UNFPA (cu...",DT.NFL.UNFP.CD,7400000.0
3169,Nigeria,NGA,2017,"Net official flows from UN agencies, WFP (curr...",DT.NFL.WFPG.CD,18510000.0
3170,Nigeria,NGA,2016,"Net official flows from UN agencies, WFP (curr...",DT.NFL.WFPG.CD,1390000.0
3181,Nigeria,NGA,2017,"Net official flows from UN agencies, WHO (curr...",DT.NFL.WHOL.CD,4510000.0
3182,Nigeria,NGA,2016,"Net official flows from UN agencies, WHO (curr...",DT.NFL.WHOL.CD,2670000.0
3183,Nigeria,NGA,2015,"Net official flows from UN agencies, WHO (curr...",DT.NFL.WHOL.CD,5770000.0

# Question 4
How much money did Nigeria receive from 
- i.) WHO in 2016 and 2017
- ii.) bilateral aid flows from DAC donor, United Kingdom in 2016 and 2017

In [75]:
un_agencies_donor = df.loc[df['indicator_name'].isin(['Net official flows from UN agencies, WHO (current US$)'])]
un_agencies_donor.head()
un_agencies_donor.loc[un_agencies_donor['year'].between(2016,2017)] 
money_recieved_in_2017 = int(un_agencies_donor.iloc[0,5])
money_recieved_in_2016 = int(un_agencies_donor.iloc[1,5])

print('amount recieved in 2017 =',money_recieved_in_2017, 'and, the amount recieved in 2016 from WHO is',money_recieved_in_2016)

western_dac_donors = df.loc[df['indicator_name'].isin([ 'Net bilateral aid flows from DAC donors, United Kingdom (current US$)'])]
western_dac_donors.head()
western_dac_donors.loc[western_dac_donors['year'].between(2016,2017)]
money_recieved_in_2017 = int(western_dac_donors.iloc[0,5])
money_recieved_in_2016 = int(western_dac_donors.iloc[1,5])

print('amount recieved in 2017 =',money_recieved_in_2017, 'and, the amount recieved in 2016 from bilateral aid flows from DAC donor,United Kingdom in 2016 and 2017 is',money_recieved_in_2016)

amount recieved in 2017 = 4510000 and, the amount recieved in 2016 from WHO is 2670000
amount recieved in 2017 = 421320000 and, the amount recieved in 2016 from bilateral aid flows from DAC donor,United Kingdom in 2016 and 2017 is 431290000

# Question 5

- i.) Calculate the mean value of all net official flows from UN agencies in 2016
- ii.) Calculate the median value of all net official flows from UN agencies in 2016

In [121]:
un_agencies_donor = df.loc[df['indicator_name'].isin(['Net official flows from UN agencies, UNICEF (current US$)',
                                                     'Net official flows from UN agencies, UNHCR (current US$)',
                                                     'Net official flows from UN agencies, UNDP (current US$)',
                                                     'Net official flows from UN agencies, UNFPA (current US$)',
                                                     'Net official flows from UN agencies, UNTA (current US$)',
                                                     'Net official flows from UN agencies, WFP (current US$)',
                                                     'Net official flows from UN agencies, WHO (current US$)'])]
un_agencies_donor.head()
un_agencies_donor[un_agencies_donor.iloc[:,2] == 2016]
from_2016 = un_agencies_donor[un_agencies_donor.iloc[:,2] == 2016]
from_2016
#c = from_2016.iloc[:,5]
#list(c)
#len(c)

,country_name,country iso code,year,indicator_name,indicator_code,value
2956,Nigeria,NGA,2016,"Net official flows from UN agencies, UNICEF (c...",DT.NFL.UNCF.CD,57920000.0
3041,Nigeria,NGA,2016,"Net official flows from UN agencies, UNDP (cur...",DT.NFL.UNDP.CD,9690000.0
3091,Nigeria,NGA,2016,"Net official flows from UN agencies, UNFPA (cu...",DT.NFL.UNFP.CD,5970000.0
3170,Nigeria,NGA,2016,"Net official flows from UN agencies, WFP (curr...",DT.NFL.WFPG.CD,1390000.0
3182,Nigeria,NGA,2016,"Net official flows from UN agencies, WHO (curr...",DT.NFL.WHOL.CD,2670000.0

In [124]:
c = from_2016.iloc[:,5]
list(c)
len(c)

5

In [125]:
np.mean(from_2016.iloc[:,5])

15528000.0

In [126]:
np.median(from_2016.iloc[:,5])

5970000.0